### ISSUE TITLE
Support for newer versions of PowerShell?

### ISSUE THREAD

**Issue by Mike-Ling** [azureinventory/ARI#12]
Hi there, you label this as compatible with the legacy Windows PowerShell (Desktop) and CloudShell, but do you officialy support PowerShell Core (6 and later) on Windows 10? I was hit by issue #11 when testing so I could not confirm but I did spot a few things that prevent use as is.

Firstly, function checkAzCli() uses Get-InstalledModule to test for the existence of the ImportExcel. From PowerShell Core, the cmdlet can not detect ImportExcel if it is installed in a Windows PowerShell folder, mine is installed to:

C:\Program Files\WindowsPowerShell\Modules\ImportExcel

I install modules that are compatible with both Desktop and Core in Desktop folders so I only have one set of modules to manage and Desktop can't import modules from a Core folder.

Changing line 73 as follows would work:
$VarExcel = Get-Module -Name ImportExcel -ListAvailable -ErrorAction SilentlyContinue

Secondly, checkAzCli() attempts to install ImportExcel if not found but does so using default settings. This attempts to install the module using the CurrentUser scope which does not work so well for my situation (which can't be unique). With folder redirection enabled, PowerShell attempts to install the module to a network drive which slows things down, but as said network drive is at the other end of a slow VPN it is pretty much unusable. I'm forced to set the scope to AllUsers so I would rather the script did not attempt to install at all.

Lastly, function checkPS() tests $PSVersionTable.PSEdition for 'Desktop' and but does not test for 'Core' so defaults to 'CloudShell' when running on 'Core'. The $Global:PSEnvironment variable is never used in the script so not sure what purpose that function serves?

Here is my PS config:

Name                                   Value
----                                        -----
PSVersion                              7.1.3
PSEdition                               Core
GitCommitId                          7.1.3
OS                                          Microsoft Windows 10.0.17763
Platform                                 Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion  2.3
SerializationVersion               1.1.0.1
WSManStackVersion              3.0

Thanks!

Mike

**Comment by Mike-Ling** [comment]
Having downgraded the resource group extension to the preview version (1.1.0) the script will now run through so with a couple of tweaks this would work just fine on PowerShell Core on Windows 10.

I also modified checkPS() to test for 'Core' so that LoginSession was executed:

![image](https://user-images.githubusercontent.com/41633781/118308581-04bd7380-b4e4-11eb-825e-33e5efde29c9.png)

**Comment by ClaudioMerola** [comment]
Hi Mike, 

wow, thanks for the troubleshooting and feedback. I updated the script with your suggestions and I believe it should work now.

Can you try it and give us a feedback?

Thanks
