### ISSUE TITLE
Latest version giving alignment errors

### ISSUE THREAD

**Issue by ajkeane-aws** [azureinventory/ARI#13]
Running the script gives the following errors - also provided the current versions of everything and I updated to the latest.

get-module importexcel

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     7.1.2      ImportExcel

$psversiontable.psversion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      1      2

az --version
azure-cli                         2.23.0
core                              2.23.0
telemetry                          1.0.6
Extensions:
resource-graph                     1.1.0

Errors-

The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

WARNING: Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
WARNING: Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
WARNING: Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.
Report Complete. Total Runtime was: .83 Minutes

**Comment by ClaudioMerola** [comment]
Hi, 

I think this error is because you were using the old version of Azure Resource Graph.

I updated the script to support the old versions too.

Can you try the version 1,4,5 and see how it goes?

Thanks

**Comment by ajkeane-aws** [comment]
Thanks -- I didn't realize I was using an outdated version.  I updated to the latest which is 2.0 and it worked.  Thanks for the quick response.
