### ISSUE TITLE
The property 'HorizontalAlignment' and 'Format' cannot be found on this object

### ISSUE THREAD

**Issue by fepere** [azureinventory/ARI#16]
Hello,
Can you please take a look on these 2 issues and let me know how I can contribute anyhow to troubleshooting..

I think is related to APIM that get failed.. maybe that´s why get this issue.

 To include Security Center details in the report, use <-SecurityCenter> parameter.

InvalidOperation: C:\Users\fpereira9\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107
Line |
 107 |  …               $Range.Style.HorizontalAlignment = $HorizontalAlignment
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and
     | can be set.

InvalidOperation: C:\Users\fpereira9\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128
Line |
 128 |  …             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'Format' cannot be found on this object. Verify that the property exists and can be set.

WARNING: Failed autosizing columns of worksheet 'APIM': You cannot call a method on a null-valued expression.
Report Complete. Total Runtime was: 5.74 Minutes
Total Resources: 15976
Total Advisories: 11115

Excel file saved at: C:\AzureResourceInventory\AzureResourceInventory_Report_2021-06-10_16_37.xlsx

PS C:\Users\fpereira9\Downloads\ARI>

**Comment by ClaudioMerola** [comment]
Hi there,

Have you ran the script before? 

Are you running it as administrator?

Do you have Az Cli installed?

Thanks

**Comment by fepere** [comment]
Hi Claudio,
Yes, I´m admin on the VM, has the latest AZ CLI installed.

PS C:\Users\fpereira9\Downloads\ARI> az --version
azure-cli                         2.24.2

core                              2.24.2
telemetry                          1.0.6

Extensions:
resource-graph                     2.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\fpereira9\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
PS C:\Users\fpereira9\Downloads\ARI>

**Comment by ClaudioMerola** [comment]
Hi,

I found an issue at line 3011 regarding the APIM Inventory.

Can you try the version 1.4.9 of the script please?

Thanks

**Comment by fepere** [comment]
Hi,
yes, I tested and the same issue with APIM.

InvalidOperation: C:\Users\fpereira9\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107
Line |
 107 |  …               $Range.Style.HorizontalAlignment = $HorizontalAlignment
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and
     | can be set.

InvalidOperation: C:\Users\fpereira9\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128
Line |
 128 |  …             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'Format' cannot be found on this object. Verify that the property exists and can be set.

WARNING: Failed autosizing columns of worksheet 'APIM': You cannot call a method on a null-valued expression.
Report Complete. Total Runtime was: 6.1 Minutes
Total Resources: 15087
Total Advisories: 10991

**Comment by ClaudioMerola** [comment]
I found an akward issue with APIM when using Network Type as None.

Can you try the version 1.4.10?

Thanks
