### ISSUE TITLE
The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.

### ISSUE THREAD

**Issue by sivaramakrishancarniprakasam** [azureinventory/ARI#17]
**\AzureResourceInventory.ps1 -TenantID ********************************* -IncludeTags -SecurityCenter**
Validating Az Cli..
Validating Az Cli Extension..
Validating ImportExcel Module..
PowerShell Desktop Identified.

 Azure Resource Inventory are collecting Security Center Advisories.
 Collecting Security Center Can increase considerably the execution time of Azure Resource Inventory and the size of final report 
 
 If you want to skip Security Center report use <-SkipSecurityCenter> parameter. 
 
The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files (x86)\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files (x86)\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
WARNING: Failed autosizing columns of worksheet 'Availability Sets': You cannot call a method on a null-valued expression.
Report Complete. Total Runtime was: 3.23 Minutes
Total Resources: 1603
Total Advisories: 1223
Total Security Advisories: 2284

**Comment by sivaramakrishancarniprakasam** [comment]
On executing the script, on the powershell console  the below message is observed.
The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files (x86)\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17

... $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : PropertyNotFound
WARNING: Failed autosizing columns of worksheet 'Availability Sets': You cannot call a method on a null-valued expression.

**Comment by ClaudioMerola** [comment]
Hi,

Can you try the version 1.4.11 and see if it is fixed?

Thanks

**Comment by sivaramakrishancarniprakasam** [comment]
I tested with Version: 1.4.11.

#This is what i have observed in output:
  
The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\0019JV744\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\0019JV744\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
WARNING: **Failed autosizing columns of worksheet 'Availability Sets': You cannot call a method on a null-valued expression.**

**Comment by ClaudioMerola** [comment]
Hi,

For some reason the Availability Set variable is returning empty for your environment. 

Can you check your Availaility Sets in Azure Portal for some Availability Set that is different or has some issue?

Thanks

**Comment by sivaramakrishancarniprakasam** [comment]
I tried for another azure tennnat:
 **Below is my observation:** 
  
The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\sam\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\sam\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
WARNING: Failed autosizing columns of worksheet 'Public IPs': You cannot call a method on a null-valued expression.
Report Complete.

Just one request,  it will be good if swich options  to incude or  exclude (VM, Publicip ......) , including sonething like -Skip Advisory for customization.

**Comment by StanleyCruvinel** [comment]
@ClaudioMerola maybe you can insert the option ``$DebugPreference`` and more stops in code to see empty values.
Use exception with Try Catch continue 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally?view=powershell-7.1 

or trap

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-7.1


@sivaramakrishancarniprakasam  

put in explicit variable in script to debug,  some time you need insert more stop debug messages. 

```
(...)
    $DebugPreference = 'Inquire'

    Extractor
    ImportDataExcel

}
(...)

**Comment by gjongeneel** [comment]
Hi, I had the exact same errors and upgraded my Azure CLI as detailed in #18 (Closed now) . After this, everything started to work like it should!
