### ISSUE TITLE
 Failed autosizing columns of worksheet 'Subscriptions' 

### ISSUE THREAD

**Issue by StanleyCruvinel** [azureinventory/ARI#18]
''
The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107 char:17
+ ...               $Range.Style.HorizontalAlignment = $HorizontalAlignment
+                   
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128 char:17
+ ...             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ ...
+                
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

WARNING: Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
WARNING: Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
WARNING: Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.
''

**Comment by StanleyCruvinel** [comment]
I don't know reason ,in line 302 get empty variable! When run outside the scrip  json has null id values and can't run  ConvertFrom-Json, in [].data has null values to id

$Resource = az graph query -q  "resources | where subscriptionId == '$SUBID' | order by id asc" --skip $Limit --first 1000 --output json --only-show-errors | ConvertFrom-Json

**Comment by StanleyCruvinel** [comment]
I found a fix, put limit lenght in properties  ``where strlen(properties) < 123000``

``$Resource = az graph query -q  "resources | where subscriptionId == '$SUBID' |  where strlen(properties) < 123000 | order by id asc" --skip $Limit --first 1000 --output json --only-show-errors | ConvertFrom-Json``

**Comment by ClaudioMerola** [comment]
Hi,

Yea, very strange behavior.

Thanks for the fix, I included it in the version 1.4.11. 

Thanks

**Comment by StanleyCruvinel** [comment]
Thanks @ClaudioMerola !
it is not perfect because exclude resources witch big strings in properties.definition.actions, like big Logic Apps. In may company 3!
