### ISSUE TITLE
Still the same issue as was referenced in #18

### ISSUE THREAD

**Issue by gjongeneel** [azureinventory/ARI#21]
When I run the script, an Excel file is generated, but there is nothing in it. During execution, the following messages appear:

<img width="656" alt="ARI" src="https://user-images.githubusercontent.com/18477985/123220811-98fcfc00-d4ce-11eb-89c2-65c512d55c12.png">

These are the exact same messages that StanleyCruvinel posted within his issue. However, in my case it does not seem to be solved with version 1.4.11

**Comment by ClaudioMerola** [comment]
Hi,

That's strange. 
Can you check what version of Resource Graph are you running?

Thanks

**Comment by gjongeneel** [comment]
I had the same error as I issue #17. After I did an upgrade to the Azure CLI 2.25.0 (from 2.24.2) by using 'az upgrade' the errors disappeared and the Excel sheet was generated correctly again.
