### ISSUE TITLE
Under the VM tab , we have duplicate entries.

### ISSUE THREAD

**Issue by sivaramakrishancarniprakasam** [azureinventory/ARI#23]
Under the VM tab , we have duplicate entries.

**Comment by ClaudioMerola** [comment]
Hi,

This is expected, probably those duplicated VMs have more than 1 IP address. Can you move to right on the spreadsheet and check if there is distinct value in some column?

If every single column is identical, then we might have a problem.

Thanks

**Comment by sivaramakrishancarniprakasam** [comment]
In my observation, the vm name was reflecting more than once. As it was Going by each and Every tag name and value.

**Comment by ClaudioMerola** [comment]
Can you check if the column "Resource U" has the value 1 or 0 on those duplicated computers?

**Comment by irlperu** [comment]
What does Resource U 1 or 0 mean in this context?

**Comment by ClaudioMerola** [comment]
Resource U is meant exactly to that, is to filter the "uniqueness" of the VMs. 1 represent the single VM
