### ISSUE TITLE
Update Azure VMs to total by disk type for HDD/SDD/Premium SDD

### ISSUE THREAD

**Issue by ajkeane-aws** [azureinventory/ARI#24]
Right now - you can mix and match disks in a vm and it will say 4 disks and 40GB of storage but this could be made up of 2 SSD's at 16GB each and 2 four GB disks of Standard HDD.  Can you update the current vm's script with this?

What I currently am doing is the following - here's a code snip and you can see all 3 types of disks broken out and totaled -

                    OsDiskSizeGB               = ""
                    OsSku                      = ""
                    TotalDiskSizeHDDStandardGB = ""
                    TotalDiskSizeSSDStandardGB = ""
                    TotalDiskSizeSSDPremiumGB  = ""
                }
                
                $info.SubscriptionName = $subscription.Name
                $info.VmName = $vm.Name 
                $info.ResourceGroupName = $vm.ResourceGroupName 
                $info.Region = $vm.Location 
                $info.VmSize = $vm.HardwareProfile.VmSize
                $info.HUBLicense = $vm.LicenseType
                $info.VirtualNetwork = $nic.IpConfigurations.subnet.Id.Split("/")[-3] 
                $info.OsType = $vm.StorageProfile.OsDisk.OsType
                $info.NicCardName = $nic.Name
                $info.Subnet = $nic.IpConfigurations.subnet.Id.Split("/")[-1] 
                $info.PrivateIpAddress = $nic.IpConfigurations.PrivateIpAddress 
                foreach ($publicIp in $publicIps) { 
                    if ($nic.IpConfigurations.id -eq $publicIp.ipconfiguration.Id) {
                        $info.PublicIPAddress = $publicIp.ipaddress
                    } 
                } 
                $info.OsType = $vm.StorageProfile.OsDisk.OsType 
                $info.OsDiskSizeGB = $vm.StorageProfile.OsDisk.diskSizeGB
                $info.OsSku = $vm.StorageProfile.ImageReference.Sku
                
                $info.TotalDiskSizeHDDStandardGB = 0
                $info.TotalDiskSizeSSDStandardGB = 0
                $info.TotalDiskSizeSSDPremiumGB = 0
                foreach ($datadisk in $vm.StorageProfile.DataDisks) {
                    if ($datadisk.ManagedDisk.StorageAccountType -eq "Standard_LRS") {
                        $info.TotalDiskSizeHDDStandardGB += $datadisk.DiskSizeGB
                    }
                    if ($datadisk.ManagedDisk.StorageAccountType -eq "StandardSSD_LRS") {
                        $info.TotalDiskSizeSSDStandardGB += $datadisk.DiskSizeGB
                    }
                    if ($datadisk.ManagedDisk.StorageAccountType -eq "Premium_LRS") {
                        $info.TotalDiskSizeSSDPremiumGB += $datadisk.DiskSizeGB
                    }
                }

**Comment by ClaudioMerola** [comment]
Hi,

We considered that when building the script. But I believe the number of lines per VM on the main VM spreadsheet is already high. That’s why we choose to include the details of disks on the “Disks” spreadsheet. To not overload the main VM spreadsheet. 

Thanks
