### ISSUE TITLE
Add Managed SQL Instances

### ISSUE THREAD

**Issue by irlperu** [azureinventory/ARI#25]
Is it possible to add SQL Managed Instances to this report as well.

Thanks!

**Comment by RenatoGregio** [comment]
hello @irlperu ,

sorry for delayed answer. 

please, try V2 that have SQL Managed instance and sent us a feedback :)

**Comment by RenatoGregio** [comment]
hello @irlperu  ,

sorry for delayed answer.

please, try V2 that have SQL Managed instance and sent us a feedback :)
