### ISSUE TITLE
Receiving Horizontal Alignment issue on latest version of the script

### ISSUE THREAD

**Issue by irlperu** [azureinventory/ARI#27]
I currently am running powershell 7.1.4

azure-cli                         2.27.1

core                              2.27.1
telemetry                          1.0.6

Extensions:
resource-graph                     2.1.0

InvalidOperation: C:\Users\ajkeane\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:107
Line |
 107 |  …               $Range.Style.HorizontalAlignment = $HorizontalAlignment
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and
     | can be set.
az account list
InvalidOperation: C:\Users\ajkeane\Documents\PowerShell\Modules\ImportExcel\7.1.2\Public\Set-ExcelRange.ps1:128
Line |
 128 |  …             $Range.Style.Numberformat.Format = (Expand-NumberFormat $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'Format' cannot be found on this object. Verify that the property exists and can be set.
https://docs.microsoft.com/en-US/cli/azure/account#az_account_set
WARNING: Failed autosizing columns of worksheet 'Subscriptions': You cannot call a method on a null-valued expression.
WARNING: Failed adding PivotTable 'P1': Index operation failed; the array index evaluated to null.
WARNING: Failed adding chart for pivotable 'P1': Cannot bind argument to parameter 'PivotTable' because it is null.

**Comment by ClaudioMerola** [comment]
Hi, 

I believe it was a bug in the last version.

Can you try the version 1.4.21?

Thanks

**Comment by irlperu** [comment]
Looks like that was the problem! thanks -
