### ISSUE TITLE
Add Service Fabric cluster

### ISSUE THREAD

**Issue by somanchirajasekhar** [azureinventory/ARI#28]
Hi All , 

 Thanks for the excellent script . It is really useful . 

Could we add service Fabric clusters ??

**Comment by RenatoGregio** [comment]
Hello @somanchirajasekhar ,

sorry for delayed answer. 
At V1 it was difficult to do. The script was big and complex. 
Now with V2 its easy and simple. 
we can create a module for Service Fabric Cluster, but we do not have a environment with SF to test. 
If you prefer you can create your module, test in your environment and sent to us to publish. 
In V2 it´s only needed to follow the template for a new module and insert then inside a Modules folder.

**Comment by RenatoGregio** [comment]
Hello @somanchirajasekhar  ,

sorry for delayed answer.
At V1 it was difficult to do. The script was big and complex.
Now with V2 its easy and simple.
we can create a module for Service Fabric Cluster, but we do not have a environment with SF to test.
If you prefer you can create your module, test in your environment and sent to us to publish.
In V2 it´s only needed to follow the template for a new module and insert then inside a Modules folder.
