### ISSUE TITLE
Testing the tool

### ISSUE THREAD

**Issue by ryansmyth2001** [azureinventory/ARI#3]
Busy testing the tool and initially was failing, i needed the latest CLI version then started running..

Guess we do have largish environment - picked up on the error below.

            {
                "code": "ResponsePayloadTooLarge",
                "message": "Response payload size is 19749321, and has exceeded the limit of 12582912. Please consider querying less data at a time and make paginated call if needed."
            }

**Comment by ClaudioMerola** [comment]
That is a very curious one, because we are already paging the results. 

Can you download the new version 1.0.4 and try it again?

Also, can you run it using the “-Debug” parameter to tell us the last debug message you got before the error happen?

**Comment by ryansmyth2001** [comment]
Sorry for delayed response - I will try again over the next few days and let you know..great tool!
