### ISSUE TITLE
Feature request: Add nat gateway inventory

### ISSUE THREAD

**Issue by rabbitfood1** [azureinventory/ARI#31]
Feature request: Add nat gateway inventory
TY

**Comment by ClaudioMerola** [comment]
Hi, 

We just launched the ARI V2 and VPN Gateway is included. Can you try it?

Thanks

**Comment by rabbitfood1** [comment]
The new version I am using is 2.1.03, it does have VPN Gateway, but I am requesting NAT Gateways and their IP/Prefixes. 
This feature:
https://docs.microsoft.com/en-us/azure/virtual-network/nat-gateway/tutorial-create-nat-gateway-portal
