### ISSUE TITLE
Run on Linux pwsh core

### ISSUE THREAD

**Issue by andrebossi** [azureinventory/ARI#4]
Tested script on Ubuntu 18.04 I'm getting follow errors

Powershell Core - 7.1.0
ImportExcel - 7.1.1
Azgraph - preview extension installed in az CLI

[log.txt](https://github.com/RenatoGregio/AzureResourceInventory/files/5679849/log.txt)

**Comment by RenatoGregio** [comment]
@andrebossi Please, 

Thank you. 

Can you Install "libgdiplus and libc6-dev" packages in your Linux and try 1.2.2 version?

Another Help, please can you sent me the output of  "$PSVersionTable.PSEdition"  command inside your PowerShell Session?



Thank you

**Comment by andrebossi** [comment]
Hi

$PSVersionTable.PSEdition = Core

Thank you
