### ISSUE TITLE
Change Conditional Format in Public IPs Sheet

### ISSUE THREAD

**Issue by camilohtaborda** [azureinventory/ARI#47]
Hello Team, I'm testing the new version of this great tool and I have a recommendation for you. The "Public IPs" Sheet have a conditional format configured on Column I for text "Underutilized". But now, this text can be found in Column J.

Is just a little change to the next version.

Have a nice day.

**Comment by ClaudioMerola** [comment]
Hi,

good catch. Fixed in today's commit (2.1.06).

Thanks
