### ISSUE TITLE
Excel is rounding Azure MySQL version

### ISSUE THREAD

**Issue by carlos-sfc** [azureinventory/ARI#55]
The Azure DB for MySQL version is rounded in the Excel file, I suggest to format the Excel sheets to stop rounding numeric values.

![image](https://user-images.githubusercontent.com/33872238/157123781-c9dc653d-e163-431a-a518-4e284258aa21.png)

**Comment by ClaudioMerola** [comment]
Hello,

You are right. 

Since we are about to release the version 2.2, we already fixed that in the new version.

We should release it in the next week. I'll let you know here once we do.

Thanks

**Comment by ClaudioMerola** [comment]
Hello,

This is fixed in version 2.2.0

Thanks
