### ISSUE TITLE
Script does not return resources

### ISSUE THREAD

**Issue by alancdias7** [azureinventory/ARI#57]
When running the script no resources are found.

I performed the execution with main service and user account.

Has anyone else gone through this?

Service Principal

![image](https://user-images.githubusercontent.com/53276043/163034840-6e33dce5-46b8-4da2-bd98-3195b1c74ffd.png)

Account

![image](https://user-images.githubusercontent.com/53276043/163035470-eba223f0-a281-4f2c-8805-eae161b835b2.png)

**Comment by ClaudioMerola** [comment]
Hi,

This seems like issues with resource-graph extension.

Can you run the script using the -Debug parameter to see if there is any issues reported?

Also, what version of the resource-graph are you running?

Thanks

**Comment by alancdias7** [comment]
Thanks for returning.

I reinstalled the AZ modules and the problem was solved.
