### ISSUE TITLE
Add Resource Group with Tags

### ISSUE THREAD

**Issue by dro7205** [azureinventory/ARI#7]
Hello,
It would be possible to easily add a tab in the Excel file with Resource Group and Tags? 

Thanks

**Comment by ClaudioMerola** [comment]
Hi,

You mean a new tab with only the Resource Group and Tags?

Thanks

**Comment by dro7205** [comment]
Yes, that's it. Thanks

**Comment by ClaudioMerola** [comment]
We just released a new version that support the parameter -IncludeTags. this will add a new column "Tags" in every resource sheet.
